name: IAC - IBM
run-name: PR - ${{ inputs.pr_number }} - ENV - ${{ inputs.environment }} - ACTION - ${{ inputs.deployment_action }} - RESOURCE - ${{ inputs.resource_name }} - FOLDER - ${{ inputs.resource_folder_name }}

on:

  workflow_dispatch:

jobs:
  cd-dev:
    name: "CD"
    uses: wolken-technik/MyLua/.github/workflows/iac-ibm-cd.yml@main
    with:
      filechanged: 'test/test.yml'
      environment: 'dev'
      pr_number: '1'
      deployment_action: 'test'
      config_data: 'test'
    secrets: inherit
