name: IAC - IBM
run-name: PR - ${{ inputs.pr_number }} - ENV - ${{ inputs.environment }} - ACTION - ${{ inputs.deployment_action }} - RESOURCE - ${{ inputs.resource_name }} - FOLDER - ${{ inputs.resource_folder_name }}

on:

  workflow_dispatch:

jobs:
  cd-dev:
    name: "CD"
    uses: wolken-technik/MyLua/.github/workflows/iac-ibm-cd.yml@main
    with:
      filechanged: '${{ inputs.pipeline_scope }}/environment/${{ inputs.environment }}/${{ inputs.resource_folder_name }}/${{ inputs.resource_name }}.yml'
      environment: ${{ inputs.environment }}
      pr_number: ${{ inputs.pr_number }}
      deployment_action: ${{ inputs.deployment_action }}
      config_data: ${{ inputs.config_data }}      
    secrets: inherit
